# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('salary', models.CharField(blank=True, max_length=250, null=True)),
                ('exp', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'ordering': ('date',),
                'verbose_name_plural': 'Jobs',
                'verbose_name': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Keywords',
                'verbose_name': 'Keyword',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lanes',
                'verbose_name': 'Lane',
            },
        ),
        migrations.CreateModel(
            name='MetaJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_type', models.CharField(default='like', max_length=250)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('position', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lane')),
            ],
            options={
                'verbose_name_plural': 'MetaJobs',
                'verbose_name': 'MetaJob',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'verbose_name': 'Skill',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.ManyToManyField(to='core.Keyword'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='core.Skill'),
        ),
    ]
