# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
