# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160709_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='exp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
