# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160825_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
