# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160722_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
