# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160731_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='metajob',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metajob',
            name='meta_type',
            field=models.CharField(default='like', max_length=250),
        ),
    ]
