# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160731_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
