# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160805_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
