# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160805_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
