# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160805_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='StackOverflow', max_length=250),
            preserve_default=False,
        ),
    ]
