# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 18:58
from __future__ import unicode_literals

import app.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160827_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('domain', models.URLField()),
                ('alexa_rank', models.IntegerField()),
                ('top_country', models.CharField(max_length=250)),
                ('month_visitors', models.IntegerField(default=0)),
                ('logo', models.ImageField(default='default.png', upload_to=app.core.models.Company.get_upload_path)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
    ]
