# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161016_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alexa_rank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='month_visitors',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='top_country_rank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
