# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161105_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='full_location',
            field=models.CharField(default='full location', max_length=250),
            preserve_default=False,
        ),
    ]
