# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state_abbreviation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
