# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161106_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
